package events

const (
	ADDED       = "added"
	CANCEL      = "cancel"
	CHANGE      = "change"
	CLEAR       = "clear"
	CLOSE       = "close"
	CLOSEING    = "closeing"
	COMPLETE    = "complete"
	CONNECT     = "connect"
	ENTER_FRAME = "enterFrame"
	EXIT_FRAME  = "exitFrame"
	FULLSCREEN  = "fullscreen"
	START       = "start"
	STOP        = "stop"
	EXIT        = "exit"
	INIT        = "init"
	OPEN        = "open"
	PASTE       = "paste"
	REMOVE      = "remove"
	RENDER      = "render"
	RESIZE      = "resize"
	SCROLL      = "scroll"
	SELECT      = "select"
	MESSAGE     = "message"

	CLICK             = "click"
	DOUBLE_CLICK      = "doubleClick"
	MIDDLE_CLICK      = "middleClick"
	MIDDLE_MOUSE_DOWN = "middleMouseDown"
	MIDDLE_MOUSE_UP   = "middleMouseUp"
	MOUSE_DOWN        = "mouseDown"
	MOUSE_UP          = "mouseUp"
	MOUSE_MOVE        = "mouseMove"
	MOUSE_WHEEL       = "mouseWheel"
	RIGHT_CLICK       = "rightClick"
	RIGHT_MOUSE_DOWN  = "rightMouseDown"
	RIGHT_MOUSE_UP    = "rightMouseUp"
	ROLL_OUT          = "rollOut"
	ROLL_OVER         = "rollOver"

	KEY_DOWN  = "keyDown"
	KEY_UP    = "keyUp"
	KEY_PRESS = "keyPress"

	UPLOADING       = "uploading"
	UPLOAD_FAIL     = "uploadFail"
	UPLOAD_COMPLETE = "uploadComplete"
	UNLOAD          = "unload"

	ERROR    = "error"
	IO_ERROR = "ioError"
)
